### PR TITLE
Add a function to fetch transfers in the account

### PR DESCRIPTION
**Pull request by adityamertia**
This function can be used to fetch transfers done in an account. Useful in fetching txHash of a transfer made.

### CODE REVIEW

**Comment by rmm5t** [comment]
@adityamertia Please add tests.

**Comment by adityamertia** [comment]
@rmm5t Kindly review.

**Comment by fb55** [comment]
This is an interesting case, as it is something the GDAX API simply proxies from Coinbase's API. Ideally you'd query Coinbase directly, eg. through [`coinbase/coinbase-node`](https://github.com/coinbase/coinbase-node). The user experience for this isn't great though, so there is a point about documenting our internal endpoints.

I'll add this to the agenda for our next internal team sync, let's see what people think.

**Comment by fb55** [comment]
Sorry for the delay. These endpoints are going to be documented, so this is good to go! :D

**Pull request merged**
