### PR TITLE
Fix BaseOrderInfo's types

### PR DESCRIPTION
**Pull request by brunoscopelliti**
Fix issue #207

### CODE REVIEW

**Comment by brunoscopelliti** [comment]
Hey @rmm5t ,
could you please give me any estimate about the time this PR would land on master. Thank you.

**Comment by rmm5t** [comment]
@brunoscopelliti Sorry, I can't answer that. I'm still waiting on commit-bit approval.

/cc @fb55

**Comment by brunoscopelliti** [comment]
Any further feedback on this?

**Comment by fb55** [comment]
Thanks a lot!

**Pull request merged**
