### PR TITLE
updated README with note on npm version usage

### PR DESCRIPTION
**Pull request by markoshust**
closes https://github.com/coinbase/gdax-node/issues/153

### CODE REVIEW

**Comment by rmm5t** [comment]
The is not the appropriate change to make for the problem of the maintainers failing to publish to NPM.

**Comment by fb55** [comment]
Agreed. We shouldn’t even mention the Github path in the first place. Right now we don’t want to publish a new release as master contains a lot of breaking changes, and a minor version bump, even if it is semver compatible, could be surprising to users. At the same time, the library isn’t in a state where we are happy to publish a 1.0 either. I’m hoping to get there in the next weeks.

**Comment by rmm5t** [comment]
> Right now we don’t want to publish a new release as master contains a lot of breaking changes, and a minor version bump, even if it is semver compatible, could be surprising to users.

@fb55 I couldn't disagree more here, because hat violates the entire purpose of semver when the major version is still `0`.  A minor version bump when the major version is still `0` implies breaking compatibility. Right now, the README documents things that are not on NPM, and that's obviously very confusing to newcomers (according to the onslaught of unnecessary Issues on this project)

It's best to continue to bump 0.x versions to NPM. Otherwise, the amount of work required for someone to upgrade from v0.4 to v1.x would be too large and daunting. It's best to have lots of little releases (even if some are backward incompatible), where someone can walk along a corresponding changelog and upgrade incrementally as as necessary.

**Comment by markoshust** [comment]
I don’t know why this PR was closed. This is a stop gap to please your user
base so they don’t get pissed off when your npm package doesn’t work as the
readme suggests it should.

Either a new 0.X version should be published as suggested, or this should
be tagged as 1.0.0 if there are no future breaks expected, even if it
doesn’t completely work. Fixes can come in 1.0.1 or 1.1.0. If you are
waiting until everything is perfect, you will be waiting a lot longer than
a few weeks.

**Comment by rmm5t** [comment]
@markoshust The PR was likely closed, because the suggested change isn't the appropriate long-term change to make. I'd argue it isn't the best short-term solution either.

> ... a new 0.X version should be published as suggested

Agreed. IMO, the appropriate approach is to resolve Issue #148 and get new versions on NPM.  At the end of the day, the tagged releases in GitHub should match what's on NPM.

**Pull request closed without merging**
