### PR TITLE
Added an option to enable the heartbeat option for the websocket.

### PR DESCRIPTION
**Pull request by OFRBG**
I did it for my own project to throttle in a cleaner way. Hope it helps.

### CODE REVIEW

**Comment by awitherow** [comment]
Would be nice to see this as a sort of 'option' in a configuration object... to me simply passing true is not very clear.

**Comment by OFRBG** [comment]
Sure. The constructor had two default parameters, one for `auth` and one for the URL. Do I wrap them in the options as well?

**Comment by awitherow** [comment]
Does that make sense to do for you @OFRBG ?

**Comment by OFRBG** [comment]
I think so. Those parameters don't look like usually-modified things, but adding them would wrap it up nicely.

**Comment by awitherow** [comment]
Then go for it @OFRBG ! keep the commit separate for using the config style object so it can be easy to compare then maybe we can get this merged soon.

**Comment by fb55** [comment]
I agree with @awitherow. Boolean arguments are always hard to read, passing an object instead is the right call.

**Comment by fb55** [comment]
Closing in favor of #76

**Pull request closed without merging**
