### PR TITLE
Get product ticker ad hoc through same client

### PR DESCRIPTION
**Pull request by daviscodesbugs**
I needed this feature to be able to interact with each market, without creating a new client connection. Might be of benefit to some users.

### CODE REVIEW

**Comment by daviscodesbugs** [comment]
Didn't run unit tests beforehand 😳. I'll remake the PR once I know it's working.

**Comment by awitherow** [comment]
@daviscodesbugs apparently you can initiatlize a public Client with a coin/currency. https://github.com/coinbase/gdax-node/pull/18

**Comment by daviscodesbugs** [comment]
@awitherow I recognized this previously, but thought it tedious to maintain multiple clients in order to perform operations such as fetch the most recent ticker.

**Comment by awitherow** [comment]
I have done something like this @daviscodesbugs https://github.com/awitherow/coinbot/pull/19/files#diff-8b7444617c652837169edb6e31a71ddaR7

**Comment by awitherow** [comment]
@daviscodesbugs do you have any ideas where we could have such similar functionality in other coin specific functions?

**Comment by daviscodesbugs** [comment]
@awitherow I don't have a specific use case personally, though it seems that being able to make certain calls, without initializing an additional client, could be useful. Perhaps a client is initialized with a default currency, but subsequent calls could take an optional parameter specifying a different currency.

**Comment by fb55** [comment]
I agree in general that having to initialize a client just to perform a request is quite hazardous. A clients functionality is basically to add a couple of defaults to methods, which could also be passed directly to the method. We might think about making the API surface flat in most cases.

**Comment by awitherow** [comment]
So does this implementation fit your ideal @fb55 ?

**Comment by fb55** [comment]
This is too limited in scope for my taste, with only a single method being updated. I'm closing this PR, but will revisit the topic. @daviscodesbugs I hope that's okay for you!

**Pull request closed without merging**
