### PR TITLE
Modernize codebase

### PR DESCRIPTION
**Pull request by fb55**
`lib/request_signer` was already using a couple of ES6 features, so this shouldn’t break anything.

Switches codebase to classes and arrow functions, replaces lodash with ES5 array extras and normalizes whitespace to four spaces.

### CODE REVIEW

**Comment by awitherow** [comment]
@fb55  what needs to be done still to get this working?

**Comment by awitherow** [comment]
Currently the test failing is

```
/home/ubuntu/gdax-node/lib/clients/public.js:58
    get(...args) {
        ^^^
```

due to unsupported rest parameters. 

Support for them is shown here: http://node.green/#ES2015-syntax-rest-parameters

They are flagged as warnings below node v6.4.0.

**Comment by awitherow** [comment]
I pulled this branch and set the node engine to `v7.8.0` and all the tests are passing!

The OrderBookSync ones looked a little bit iffy, they took a while to complete.

```javascript
  ✓ OrderbookSync public client should stream trades: 2784ms
  ✓ OrderbookSync public client should stream trades with function: 3365ms
```

**Comment by awitherow** [comment]
ping @fb55

**Comment by awitherow** [comment]
ping @mihar @fb55 ? anyone alive?

**Comment by awitherow** [comment]
@fb55 I would really like to work on getting this merged and working, is there something we can do to get this happening or can the community here get an update at least of what is going on? I have pinged you guys multiple times over the last 2 months... Can we be a little more professional about this?

**Comment by fb55** [comment]
@awitherow I didn't have a chance to investigate the performance regressions at the time, which is why I didn't pursue it any further. I would love it if someone could take this over.

**Comment by nikulis** [comment]
In looking at updating tests for my own refactoring, I found that the current tests for `PublicClient#getProductTradeStream` were actually going to the network / live GDAX API instead of mocking the requests through nock. The variability of the network and live API timing is likely what lead to the difference in execution time.

I've opened a new PR #55 that has a local copy of the requests for nock to use (I used `nock.recorder.rec()` and friends to record the live API calls and save them to a nock config json that could by loaded in tests.)

**Comment by awitherow** [comment]
@fb55 thank you for the response!

Do you guys do any standardized performance testing for gdax-node already, or would we have to create a standard now?

**Comment by fb55** [comment]
@nikulis That's a great find, thanks for looking into it!

@awitherow We don't have anything like that for `gdax-node` right now. The existing tests already help to spot large changes, having some proper benchmarks would be great though.

**Comment by awitherow** [comment]
This would be a learning exercise in terms of how to do benchmark testing & performance stuff... So I am just shooting ideas and needing a little guidance.

Would integration of something like this:

https://benchmarkjs.com

Into the test suite help to track things in the future well?

We could then even write the statistics to json and be able to see the trends in speed of the test suite over time?

Is there a better way to do this?

**Comment by awitherow** [comment]
Also, what is to be done about the node version of the project? With the refactorings, a higher default node version is necessary for the code to even properly function. Thoughts on using v8.0.0?

**Comment by fb55** [comment]
Closing in favor of #60

**Pull request closed without merging**
