### PR TITLE
Add description for getAccountTransfers function

### PR DESCRIPTION
**Pull request by adityamertia**
Add description of how to use getAccountTransfers function

### CODE REVIEW

**Comment by rmm5t** [comment]
Could you please merge this into #217? Also, in the example, please don't assign the `accountID` variable. Just mimick the other examples.

**Comment by adityamertia** [comment]
Sure i will merge this into #217 PR. Will close this PR. However just to clarify i just copied the README content from getAccountHistory and modified the name. The accountID assignment was there already. Could you pls clarify what you meant?

**Comment by rmm5t** [comment]
> The accountID assignment was there already. Could you pls clarify what you meant?

Ignore what I said there. My mistake.

**Comment by adityamertia** [comment]
Sure. Kindly check #217 and merge to master.

**Pull request closed without merging**
