### PR TITLE
optionally specify productId in authenticated client constructor, passing to public client

### PR DESCRIPTION
**Pull request by mattstabeler**
Edit: as mentioned by @MarcSallent, this solves the issue of not being able to specify a `productId` for methods of `PublicClient` that is inherited by `AuthenticatedClient`

### CODE REVIEW

**Comment by mihar** [comment]
Can you add a description why this is good?

**Comment by MarcSallent** [comment]
Some public methods, like `getProductTicker` depend on the `productId` specified in the initialization of `PublicClient`.
At this moment, when `PublicClient` is inherited by `AuthenticatedClient`, no  `productId` is specified, defaulting to `BTC-USD`
This pull request would solve it.

**Comment by mihar** [comment]
OK, looks good. Can you update the README as well.

**Comment by mattstabeler** [comment]
Hi @mihar I have updated the README updated with the new parameters.

**Comment by fb55** [comment]
@mattstabeler This needs a rebase, otherwise lgtm

**Comment by fb55** [comment]
Superseded by #83 — thanks @mattstabeler for kicking this off.

**Pull request closed without merging**
